# Change these first
owner: myc-rmt # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: EGU - Dota 2 News
    url: https://my-egu.vercel.app/api/news/scrapeGoogle?topic=Dota%202
  - name: EGU - League of Legends News
    url: https://my-egu.vercel.app/api/news/scrapeGoogle?topic=League%20of%20Legends
  - name: EGU - Counter-Strike%3A Global Offensive News
    url: https://my-egu.vercel.app/api/news/scrapeGoogle?topic=Counter-Strike%3A%20Global%20Offensive
  - name: EGU - Fortnite News
    url: https://my-egu.vercel.app/api/news/scrapeGoogle?topic=Fortnite
  - name: EGU - Apex Legends News
    url: https://my-egu.vercel.app/api/news/scrapeGoogle?topic=Apex%20Legends
  - name: EGU - VALORANT News
    url: https://my-egu.vercel.app/api/news/scrapeGoogle?topic=VALORANT
  - name: EGU - PLAYERUNKNOWN%27S BATTLEGROUNDS News
    url: https://my-egu.vercel.app/api/news/scrapeGoogle?topic=PLAYERUNKNOWN%27S%20BATTLEGROUNDS
  - name: EGU - Overwatch News
    url: https://my-egu.vercel.app/api/news/scrapeGoogle?topic=Overwatch
  - name: EGU - Call of Duty News
    url: https://my-egu.vercel.app/api/news/scrapeGoogle?topic=Call%20of%20Duty
  - name: FRESHFACES
    url: https://freshfaces.vercel.app/api/cron/ping

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
